> 📅 Learning Progress: Day 10 of my Machine Learning journey. This is about Tensor Operations in Python。

In [2]:
# This part is basic introduction of numpy array, which is the fundamental package for scientific computing with Python. 
import numpy as np
list1 = [1, 2, 3, 4, 5]
array_1=np.array(list1) #convert the list to numpy array
array_2=np.array((6,7,8,9,10)) #convert the tuple to numpy array
array_3=np.array([[1,2,3],[4,5,6]]) #convert the list of lists to 2D numpy array
print("convert the list to numpy array:",array_1)
print("convert the tuple to numpy array:",array_2)
print("convert the list of lists to 2D numpy array:",array_3)
#The reason for using numpy array instead of list.
print("the shape of array_1:",array_1.shape) #print the shape of array_1
# print("the shape of list1",list1.shape) #This is not a numpy array, so it does not have shape attribute, it will raise an error.

convert the list to numpy array: [1 2 3 4 5]
convert the tuple to numpy array: [ 6  7  8  9 10]
convert the list of lists to 2D numpy array: [[1 2 3]
 [4 5 6]]
the shape of array_1: (5,)


In [ ]:
#some useful functions to create numpy array, arange and linspace.
array_4=np.arange(1,5,1) #create a numpy array with values from 1 to 4 with step size of 1
array_5=np.linspace(1,5,5) #create a numpy array with 5 values from 1 to 5 with equal spacing
print(array_4)
print(array_5)

array_6=np.arange(10)
print("the contents of array_6:",array_6)
#slicing
from tensorflow.keras.datasets import mnist #import mnist dataset from keras.datasets
(x_train,y_train),(x_test,y_test)=mnist.load_data() #load the mnist dataset.
print("Shape of x_train:", x_train.shape)
x_train_slice=x_train[10000:15000, :,:] #slice the x_train from 10000 to 15000, and all the rows and columns
print("Shape of x_train_slice:", x_train_slice.shape)


[1 2 3 4]
[1. 2. 3. 4. 5.]
the contents of array_6: [0 1 2 3 4 5 6 7 8 9]
Shape of x_train: (60000, 28, 28)
Shape of x_train_slice: (5000, 28, 28)


In [ ]:
array_