> 📅 Learning Progress: Day 8 of my Machine Learning journey

In [ ]:
#Scalar, 0-rank tensor/0-dimensional tensor
import numpy as np
x =np.array(5)
print("The value of x:",x)
print("The rank of x:",x.ndim)
print("The data type of x:",x.dtype)
print("The shape of x:",x.shape)


The value of x: 5
The rank of x: 0
The data type of x: int64
The shape of x: ()
The value of gender: 0
The value of gender: 1


In [ ]:
#Vector, 1-rank tensor/1-dimensional tensor
y = np.array([1,2,3,4,5]) #This is a 1-dimensional tensor with 5 elements.
print("The value of y:",y)
print("The rank of y:",y.ndim)
print("The data type of y:",y.dtype)
print("The shape of y:",y.shape) #It is 5-dimensional vector.

#Vector dataset in ML
from tensorflow.keras.datasets import boston_housing
(x_train, y_train), (x_test, y_test) = boston_housing.load_data()
print("The shape of x_train:",x_train.shape) #It is 404-dimensional vector.
print("The shape of the first sample of x_train:",x_train[0].shape) #It is 13-dimensional vector.
print("The shape of y_train:",y_train.shape) #It is 404-dimensional vector.

# Dot product of two vectors
a = np.array([1,-1.8,1,1,2])
b = np.array([1,6,7,8,9])
output = np.dot(a,b) #This is the dot product of two vectors a and b.

print("The dot product of a and b:",output)



The value of y: [1 2 3 4 5]
The rank of y: 1
The data type of y: int64
The shape of y: (5,)
The shape of x_train: (404, 13)
The shape of the first sample of x_train: (13,)
The shape of y_train: (404,)
The dot product of a and b: 23.2
The dot product of b and a: 23.2


In [7]:
#Matrix, 2-rank tensor/2-dimensional tensor
# Matrix is a 2-dimensional tensor,the shape is (samples, features), where samples is the number of samples in the dataset, and features is the number of features in each sample.
print("the contents of x_train:",x_train)
print("the shape of x_train:",x_train.shape)


the contents of x_train: [[1.23247e+00 0.00000e+00 8.14000e+00 ... 2.10000e+01 3.96900e+02
  1.87200e+01]
 [2.17700e-02 8.25000e+01 2.03000e+00 ... 1.47000e+01 3.95380e+02
  3.11000e+00]
 [4.89822e+00 0.00000e+00 1.81000e+01 ... 2.02000e+01 3.75520e+02
  3.26000e+00]
 ...
 [3.46600e-02 3.50000e+01 6.06000e+00 ... 1.69000e+01 3.62250e+02
  7.83000e+00]
 [2.14918e+00 0.00000e+00 1.95800e+01 ... 1.47000e+01 2.61950e+02
  1.57900e+01]
 [1.43900e-02 6.00000e+01 2.93000e+00 ... 1.56000e+01 3.76700e+02
  4.38000e+00]]
the shape of x_train: (404, 13)


In [9]:
#Create 3-rank tensor/3-dimensional tensor
c = np.array([[[1,22,4,78,2],[2,59,6,56,1],[3,31,8,54,0]],[[4,56,9,34,1],[5,78,8,35,2],[6,34,7,36,0]],[[7,12,6,37,1],[8,45,5,38,2],[9,23,4,39,0]]])
print("the contents of c:",c)
# In 2-dimensional tensor, the shape is samples and features, but in 3-dimensional tensor, the shape is samples, timesteps and features. 
# In this case, the shape of c is (3, 3, 5), where 3 is the number of samples, 3 is the number of timesteps, and 5 is the number of features.
print("the shape of c:",c.shape)

the contents of c: [[[ 1 22  4 78  2]
  [ 2 59  6 56  1]
  [ 3 31  8 54  0]]

 [[ 4 56  9 34  1]
  [ 5 78  8 35  2]
  [ 6 34  7 36  0]]

 [[ 7 12  6 37  1]
  [ 8 45  5 38  2]
  [ 9 23  4 39  0]]]
the shape of c: (3, 3, 5)


In [ ]:
# Image dataset, 4-rank tensor/4-dimensional tensor
# Image dataset MNIST is one of the example of 4-dimensional tensor, the shape is (samples, height, width, channels), 
# where samples is the number of images in the dataset, height and width are the dimensions of the image, and channels is the number of color channels in the image (1 for grayscale, 3 for RGB).

# video dataset, 5-rank tensor/5-dimensional tensor
# Video dataset is an example of 5-dimensional tensor, the shape is (samples, timesteps, height, width, channels)

